-- Create database
CREATE DATABASE IF NOT EXISTS pet_adoption_db;
USE pet_adoption_db;

-- Create adopters table
CREATE TABLE IF NOT EXISTS adopters (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    contact VARCHAR(50) NOT NULL,
    address VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create pets table
CREATE TABLE IF NOT EXISTS pets (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    breed VARCHAR(100) NOT NULL,
    adopted BOOLEAN NOT NULL DEFAULT FALSE,
    breedable BOOLEAN NOT NULL DEFAULT FALSE,
    diseases VARCHAR(255),
    adopter_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (adopter_id) REFERENCES adopters(id) ON DELETE SET NULL
);